;)

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -125,10 +125,10 @@ jobs:
       - run:
           name: Smoke Test
           command: |
-            HTTPCODE=curl -s -o /dev/null -w "%{http_code}" https://nameless-woodland-24979.herokuapp.com/
-            if [[ "$HTTPCODE" -ne 200 ]]; then
-              echo "heroku app not responding, failing deploy" \
-              exit 1; \
+            HTTPCODE=`curl -s -o /dev/null -w "%{http_code}" https://nameless-woodland-24979.herokuapp.com/`
+            if [ "$HTTPCODE" -ne 200 ];then
+            echo "heroku app not responding, failing deploy"
+            exit 1
             fi
 
 workflows:
